2.1. Data Manipulation

In [1]:
import torch
x=torch.arange(12,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [2]:
x.numel()

12

In [3]:
x.shape

torch.Size([12])

In [4]:
X=x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [5]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
torch.randn(3,4)

tensor([[ 1.3181,  0.5587,  0.5885, -1.9484],
        [-1.0617,  0.6824,  0.0790,  0.4078],
        [ 0.7572,  1.2550,  1.5694, -0.0188]])

In [8]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [9]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [10]:
X[1,2]=17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
X[:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [12]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [13]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
X==Y,X<Y,X>Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [16]:
X.sum()

tensor(66.)

In [17]:
a=torch.arange(1,4).reshape((3,1))
b=torch.arange(1,3).reshape((1,2))
a,b

(tensor([[1],
         [2],
         [3]]),
 tensor([[1, 2]]))

In [18]:
a+b,a-b,a*b,a/b,a//b,a%b,a**b

(tensor([[2, 3],
         [3, 4],
         [4, 5]]),
 tensor([[ 0, -1],
         [ 1,  0],
         [ 2,  1]]),
 tensor([[1, 2],
         [2, 4],
         [3, 6]]),
 tensor([[1.0000, 0.5000],
         [2.0000, 1.0000],
         [3.0000, 1.5000]]),
 tensor([[1, 0],
         [2, 1],
         [3, 1]]),
 tensor([[0, 1],
         [0, 0],
         [0, 1]]),
 tensor([[1, 1],
         [2, 4],
         [3, 9]]))

In [19]:
before=id(Y)
Y=Y+X
id(Y)==before

False

In [20]:
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('id(Z):',id(Z))

id(Z): 1731664745136
id(Z): 1731664745136


In [21]:
before=id(X)
X+=Y
id(X)==before

True

In [22]:
A=X.numpy()
B=torch.from_numpy(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [23]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

2.2. Data Preprocessing

In [10]:
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [11]:
import pandas as pd

data=pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [12]:
inputs,target=data.iloc[:,0:2],data.iloc[:,2]
inputs=pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN               0             1
1       2.0               0             1
2       4.0               1             0
3       NaN               0             1


In [13]:
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0               0             1
1       2.0               0             1
2       4.0               1             0
3       3.0               0             1


In [14]:
import torch

X=torch.tensor(inputs.to_numpy(),dtype=float)
y=torch.tensor(target.to_numpy(),dtype=float)
X,y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

2.3. Linear Algebra

In [16]:
import torch

In [17]:
x=torch.tensor(3.0)
y=torch.tensor(2.0)

x+y,x*y,x/y,x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [18]:
x=torch.arange(3)
x

tensor([0, 1, 2])

In [19]:
x[2]

tensor(2)

In [20]:
len(x)

3

In [21]:
x.shape

torch.Size([3])

In [23]:
A=torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [24]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [26]:
A=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A==A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [27]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [28]:
A=torch.arange(6,dtype=torch.float32).reshape(2,3)
B=A.clone()
A,A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [29]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [30]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [31]:
x=torch.arange(3,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [32]:
A.shape,A.sum()

(torch.Size([2, 3]), tensor(15.))

In [33]:
A.shape,A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [34]:
A.shape,A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [35]:
A.sum(axis=[0,1])==A.sum() #Same as A.sum()

tensor(True)

In [36]:
A.mean(),A.sum()/A.numel()

(tensor(2.5000), tensor(2.5000))

In [37]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [38]:
sum_A=A.sum(axis=1,keepdims=True)
sum_A,sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [39]:
A/sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [40]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [41]:
y=torch.ones(3,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [42]:
torch.sum(x*y)

tensor(3.)

In [43]:
A.shape,x.shape,torch.mv(A,x),A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [44]:
B=torch.ones(3,4)
torch.mm(A,B),A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [45]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [46]:
torch.abs(u).sum()

tensor(7.)

In [47]:
torch.norm(torch.ones((4,9)))

tensor(6.)

2.5. Automatic Differentiation

In [48]:
import torch

In [49]:
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [50]:
# Can also create x=torch.arange(4.0,requires_grad=True)
x.requires_grad_(True)
x.grad # The gradient is None by default

In [51]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [52]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [53]:
x.grad==4*x

tensor([True, True, True, True])

In [54]:
x.grad.zero_() #Reset the gradient
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [55]:
x.grad.zero_()
y=x*x
y.backward(gradient=torch.ones(len(y))) # Faster: y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [56]:
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x

z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [57]:
x.grad.zero_()
y.sum().backward()
x.grad==2*x

tensor([True, True, True, True])

In [58]:
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c

In [59]:
a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()

In [60]:
a.grad==d/a

tensor(True)